INSERT INTO category (CATEGORY_ID,CATEGORY_NAME) VALUES (1,'Fashion');

INSERT INTO category (CATEGORY_ID,CATEGORY_NAME) VALUES (2,'Electronics');

INSERT INTO category (CATEGORY_ID,CATEGORY_NAME) VALUES (3,'Books');

INSERT INTO category (CATEGORY_ID,CATEGORY_NAME) VALUES (4,'Groceries'); 

INSERT INTO category (CATEGORY_ID,CATEGORY_NAME) VALUES (5,'Medicines');

INSERT INTO USER (user_id,USERNAME, PASSWORD) VALUES (1,'jack', 'pass_word');

INSERT INTO USER (user_id,USERNAME, PASSWORD) VALUES (2,'bob', 'pass_word'); 

INSERT INTO user (user_id,USERNAME, PASSWORD) VALUES (3,'apple', 'pass_word');

INSERT INTO USER (user_id,USERNAME, PASSWORD) VALUES (4,'glaxo', 'pass_word');

INSERT INTO CART (cart_id,TOTAL_AMOUNT, USER_USER_ID) VALUES (1,20, 1); 

INSERT INTO CART (cart_id,TOTAL_AMOUNT, USER_USER_ID) VALUES (2,0, 2);

INSERT INTO USER_ROLE (USER_ID, ROLES) VALUES (1, 'ROLE_CONSUMER');

INSERT INTO USER_ROLE (USER_ID, ROLES) VALUES (2, 'ROLE_CONSUMER');

INSERT INTO USER_ROLE (USER_ID, ROLES) VALUES (3, 'ROLE_SELLER');

INSERT INTO USER_ROLE (USER_ID, ROLES) VALUES (4, 'ROLE_SELLER');

INSERT INTO PRODUCT (product_id,PRICE, PRODUCT_NAME,CATEGORY_ID,SELLER_ID) VALUES (1,29198, 'Apple iPad 10.2 8th Gen WiFi 105 Tablet', 2, 3);

INSERT INTO PRODUCT (product_id,PRICE, PRODUCT_NAME,CATEGORY_ID,SELLER_ID) VALUES (2,10, 'Crocin pain relief tablet', 5, 4);

INSERT INTO CART_PRODUCT (cp_id,CART_ID,PRODUCT_ID,QUANTITY) VALUES (1,1,2,2);
